name: Publish

on:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Attach artifacts to GitHub release
        run: ./gradlew githubRelease
        env:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: doc
